---
title: "rTTManAPI"
author: "Yury Maisiayonak"
date: "`r Sys.time()`"
output: html_document
params: 
    server: "exchange.tts.st.soft-fx.eu"
    login: "12351"
    password: "123qwe!"
    startTime: "2017-04-29"
    endTime: "2017-08-04"
---

```{r cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE, results='hide'}
library(lubridate) 
library(data.table) 
library(foreach) 
library(DT) 
library(plotly) 
library(knitr)
library(rTTManApi)
options(scipen = 999)
extract_help <- function(pkg, fn = NULL)
{
       rdbfile <- file.path(find.package(pkg), "help", pkg)
       rdb <- tools:::fetchRdDB(rdbfile, key = fn)
}
helper = extract_help("rTTManApi")
from<-as.Date(params$startTime)
to <- as.Date(params$endTime)
```

###Parameters
Server: _`r params$server`_.

Login: _`r params$login`_.

Password: _`r params$password`_.

Period: _`r as.Date(from)`_ - _`r as.Date(to)`_.

##ttmConnect
```{r message = FALSE, warning=FALSE}
ttmConnect(params$server, params$login, params$password)
```
```{r  echo = FALSE}
print(helper$ttmConnect[[1]][[1]][[1]][1])
```
##ttmGetAllAccounts
```{r}
accounts = ttmGetAllAccounts()
```
```{r  echo = FALSE}
print(helper$ttmGetAllAccounts[[1]][[1]][[1]][1])
datatable(accounts)
```

##ttmGetAllGroups
```{r}
groups = ttmGetAllGroups()
```
```{r  echo = FALSE}
print(helper$ttmGetAllGroups[[1]][[1]][[1]][1])
datatable(groups)
```

##ttmGetAllOrders
```{r}
orders = ttmGetAllOrders()
```
```{r  echo = FALSE}
print(helper$ttmGetAllOrders[[1]][[1]][[1]][1])
datatable(orders)
```

##ttmGetAssets
```{r warning=TRUE}
assets = ttmGetAssets(as.character(accounts[AccountingType == "Cash"]$Login[1]))
```
```{r  echo = FALSE}
print(helper$ttmGetAssets[[1]][[1]][[1]][1])
datatable(assets)
```

##ttmGetAssetsSnapshots
```{r}
assetsSnapshots = ttmGetAssetSnapshots(as.character(accounts[AccountingType == "Cash"]$Login))
```
```{r  echo = FALSE}
print(helper$ttmGetAssetSnapshots[[1]][[1]][[1]][1])
datatable(assetsSnapshots)
```

##ttmGetOrders
```{r}
order = ttmGetOrders(as.character(accounts$Login[1]))
```
```{r  echo = FALSE}
print(helper$ttmGetOrders[[1]][[1]][[1]][1])
datatable(order)
```

##ttmGetTradeReports
```{r}
tradesReports = ttmGetTradeReports(as.character(accounts$Login))
```
```{r  echo = FALSE}
print(helper$ttmGetTradeReports[[1]][[1]][[1]][1])
datatable(tradesReports)
```

##ttmDisconnect
```{r}
ttmDisconnect()
```
```{r  echo = FALSE}
print(helper$ttmDisconnect[[1]][[1]][[1]][1])
```
